
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 25 20:48:41 EDT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 50;
  public static final int IDENTIFIER = 76;
  public static final int SUBROUTINE = 12;
  public static final int GTHANE = 60;
  public static final int CONSTRUCTOR = 11;
  public static final int HASHMAP = 17;
  public static final int COMMA = 51;
  public static final int RBRACE = 69;
  public static final int RPAREN = 71;
  public static final int INCREMENT = 58;
  public static final int GETFLOAT = 40;
  public static final int SAGE = 4;
  public static final int LBRACE = 68;
  public static final int LPAREN = 70;
  public static final int PROTECTED = 8;
  public static final int FALSE = 33;
  public static final int NOR = 30;
  public static final int NIL = 35;
  public static final int FLOAT = 15;
  public static final int GETSTRING = 42;
  public static final int MOD = 57;
  public static final int CLASS = 9;
  public static final int STRINGLITERAL = 75;
  public static final int FLOATLITERAL = 78;
  public static final int TRUE = 32;
  public static final int PLUS = 52;
  public static final int EXEC = 48;
  public static final int WHILE = 23;
  public static final int EQUAL = 64;
  public static final int EXTENDS = 10;
  public static final int BOOLEAN = 16;
  public static final int DO = 25;
  public static final int FOR = 24;
  public static final int VOID = 13;
  public static final int DIV = 55;
  public static final int PUBLIC = 6;
  public static final int RETURN = 26;
  public static final int MULT = 54;
  public static final int ELSE = 20;
  public static final int GTHAN = 63;
  public static final int BREAK = 46;
  public static final int DOT = 72;
  public static final int INT = 14;
  public static final int LENGTH = 43;
  public static final int POWER = 56;
  public static final int INTLITERAL = 77;
  public static final int SEMICOLON = 73;
  public static final int EOF = 0;
  public static final int THIS = 34;
  public static final int BANG = 65;
  public static final int LTHAN = 62;
  public static final int PRINT = 44;
  public static final int DECREMENT = 59;
  public static final int GETBOOLEAN = 41;
  public static final int MINUS = 53;
  public static final int DEBUG = 45;
  public static final int OR = 28;
  public static final int error = 1;
  public static final int EXIT = 38;
  public static final int START = 2;
  public static final int CONTINUE = 47;
  public static final int IF = 19;
  public static final int LTHANE = 61;
  public static final int END = 3;
  public static final int COLON = 74;
  public static final int RATHER = 22;
  public static final int ASSERT = 36;
  public static final int USING = 5;
  public static final int CREATE = 37;
  public static final int RBRACKET = 67;
  public static final int BEGIN = 21;
  public static final int STRING = 18;
  public static final int AND = 27;
  public static final int PRIVATE = 7;
  public static final int GETINT = 39;
  public static final int LBRACKET = 66;
  public static final int WITH = 49;
  public static final int NAND = 29;
  public static final int EQUALS = 31;
}

