
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 14 20:20:27 EDT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 45;
  public static final int IDENTIFIER = 69;
  public static final int POINTER = 44;
  public static final int SUBROUTINE = 7;
  public static final int GTHANE = 53;
  public static final int HASHMAP = 12;
  public static final int COMMA = 46;
  public static final int RBRACE = 62;
  public static final int RPAREN = 64;
  public static final int GETFLOAT = 36;
  public static final int SAGE = 4;
  public static final int LBRACE = 61;
  public static final int LPAREN = 63;
  public static final int FALSE = 29;
  public static final int NOR = 26;
  public static final int NIL = 31;
  public static final int ARRAY = 14;
  public static final int FLOAT = 10;
  public static final int GETSTRING = 38;
  public static final int MOD = 52;
  public static final int CLASS = 5;
  public static final int STRINGLITERAL = 68;
  public static final int FLOATLITERAL = 71;
  public static final int TRUE = 28;
  public static final int PLUS = 47;
  public static final int WHILE = 19;
  public static final int EQUAL = 57;
  public static final int EXTENDS = 6;
  public static final int BOOLEAN = 11;
  public static final int DO = 21;
  public static final int FOR = 20;
  public static final int VOID = 8;
  public static final int DIV = 50;
  public static final int RETURN = 22;
  public static final int MULT = 49;
  public static final int ELSE = 16;
  public static final int GTHAN = 56;
  public static final int BREAK = 42;
  public static final int DOT = 65;
  public static final int INT = 9;
  public static final int LENGTH = 39;
  public static final int POWER = 51;
  public static final int INTLITERAL = 70;
  public static final int EOF = 0;
  public static final int SEMICOLON = 66;
  public static final int THIS = 30;
  public static final int BANG = 58;
  public static final int LTHAN = 55;
  public static final int PRINT = 40;
  public static final int GETBOOLEAN = 37;
  public static final int MINUS = 48;
  public static final int DEBUG = 41;
  public static final int OR = 24;
  public static final int error = 1;
  public static final int EXIT = 34;
  public static final int START = 2;
  public static final int CONTINUE = 43;
  public static final int IF = 15;
  public static final int LTHANE = 54;
  public static final int END = 3;
  public static final int COLON = 67;
  public static final int RATHER = 18;
  public static final int ASSERT = 32;
  public static final int CREATE = 33;
  public static final int RBRACKET = 60;
  public static final int BEGIN = 17;
  public static final int STRING = 13;
  public static final int AND = 23;
  public static final int GETINT = 35;
  public static final int LBRACKET = 59;
  public static final int NAND = 25;
  public static final int EQUALS = 27;
}

