
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 19 22:24:39 EDT 2018
//----------------------------------------------------

package lexer_parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 58;
  public static final int IDENTIFIER = 85;
  public static final int POINTER = 60;
  public static final int TYPEOF = 53;
  public static final int CONST = 22;
  public static final int SUBROUTINE = 14;
  public static final int UNTIL = 31;
  public static final int GTHANE = 69;
  public static final int CONSTRUCTOR = 11;
  public static final int CATCH = 55;
  public static final int HASHMAP = 19;
  public static final int COMMA = 59;
  public static final int RBRACE = 78;
  public static final int THROW = 57;
  public static final int RPAREN = 80;
  public static final int INCREMENT = 67;
  public static final int SAGE = 4;
  public static final int LBRACE = 77;
  public static final int LPAREN = 79;
  public static final int PROTECTED = 8;
  public static final int FALSE = 40;
  public static final int NOR = 36;
  public static final int NIL = 42;
  public static final int VAR = 21;
  public static final int FLOAT = 17;
  public static final int MOD = 66;
  public static final int CLASS = 9;
  public static final int STRINGLITERAL = 84;
  public static final int SUPER = 12;
  public static final int UNLESS = 27;
  public static final int FLOATLITERAL = 87;
  public static final int TRUE = 39;
  public static final int PLUS = 61;
  public static final int EXEC = 51;
  public static final int EQUAL = 73;
  public static final int WHILE = 28;
  public static final int EXTENDS = 10;
  public static final int BOOLEAN = 18;
  public static final int DO = 30;
  public static final int FOR = 29;
  public static final int VOID = 15;
  public static final int DIV = 64;
  public static final int PUBLIC = 6;
  public static final int RETURN = 32;
  public static final int MULT = 63;
  public static final int ELSE = 24;
  public static final int TRY = 54;
  public static final int GTHAN = 72;
  public static final int BREAK = 49;
  public static final int DOT = 81;
  public static final int INT = 16;
  public static final int LENGTH = 46;
  public static final int POWER = 65;
  public static final int INTLITERAL = 86;
  public static final int SEMICOLON = 82;
  public static final int EOF = 0;
  public static final int BANG = 74;
  public static final int LTHAN = 71;
  public static final int THIS = 41;
  public static final int PRINT = 47;
  public static final int DECREMENT = 68;
  public static final int MINUS = 62;
  public static final int DEBUG = 48;
  public static final int OR = 34;
  public static final int error = 1;
  public static final int EXIT = 45;
  public static final int START = 2;
  public static final int FINALLY = 56;
  public static final int CONTINUE = 50;
  public static final int IF = 23;
  public static final int LTHANE = 70;
  public static final int END = 3;
  public static final int COLON = 83;
  public static final int RATHER = 26;
  public static final int ASSERT = 43;
  public static final int USING = 5;
  public static final int CREATE = 44;
  public static final int RBRACKET = 76;
  public static final int BEGIN = 25;
  public static final int STRING = 20;
  public static final int AND = 33;
  public static final int PRIVATE = 7;
  public static final int DIFFERS = 38;
  public static final int STATIC = 13;
  public static final int LBRACKET = 75;
  public static final int WITH = 52;
  public static final int NAND = 35;
  public static final int EQUALS = 37;
}

