
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 29 21:02:58 EDT 2018
//----------------------------------------------------

package lexer_parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 60;
  public static final int IDENTIFIER = 87;
  public static final int POINTER = 62;
  public static final int TYPEOF = 55;
  public static final int CONST = 22;
  public static final int SUBROUTINE = 14;
  public static final int UNTIL = 32;
  public static final int GTHANE = 71;
  public static final int DELEGATE = 23;
  public static final int CONSTRUCTOR = 11;
  public static final int CATCH = 57;
  public static final int HASHMAP = 19;
  public static final int COMMA = 61;
  public static final int RBRACE = 80;
  public static final int THROW = 59;
  public static final int RPAREN = 82;
  public static final int INCREMENT = 69;
  public static final int SAGE = 4;
  public static final int LBRACE = 79;
  public static final int LPAREN = 81;
  public static final int PROTECTED = 8;
  public static final int FALSE = 43;
  public static final int NOR = 39;
  public static final int NIL = 45;
  public static final int VAR = 21;
  public static final int FLOAT = 17;
  public static final int MOD = 68;
  public static final int CLASS = 9;
  public static final int STRINGLITERAL = 86;
  public static final int SUPER = 12;
  public static final int UNLESS = 28;
  public static final int FLOATLITERAL = 89;
  public static final int TRUE = 42;
  public static final int PLUS = 63;
  public static final int EXEC = 54;
  public static final int EQUAL = 75;
  public static final int WHILE = 29;
  public static final int EXTENDS = 10;
  public static final int BOOLEAN = 18;
  public static final int DO = 31;
  public static final int FOR = 30;
  public static final int VOID = 15;
  public static final int DIV = 66;
  public static final int PUBLIC = 6;
  public static final int RETURN = 35;
  public static final int MULT = 65;
  public static final int ELSE = 25;
  public static final int TRY = 56;
  public static final int GTHAN = 74;
  public static final int BREAK = 52;
  public static final int DOT = 83;
  public static final int INT = 16;
  public static final int LENGTH = 49;
  public static final int POWER = 67;
  public static final int INTLITERAL = 88;
  public static final int SEMICOLON = 84;
  public static final int EOF = 0;
  public static final int BANG = 76;
  public static final int LTHAN = 73;
  public static final int THIS = 44;
  public static final int PRINT = 50;
  public static final int DECREMENT = 70;
  public static final int MINUS = 64;
  public static final int IN = 34;
  public static final int DEBUG = 51;
  public static final int OR = 37;
  public static final int error = 1;
  public static final int EXIT = 48;
  public static final int START = 2;
  public static final int FINALLY = 58;
  public static final int CONTINUE = 53;
  public static final int IF = 24;
  public static final int LTHANE = 72;
  public static final int END = 3;
  public static final int COLON = 85;
  public static final int RATHER = 27;
  public static final int ASSERT = 46;
  public static final int USING = 5;
  public static final int CREATE = 47;
  public static final int FOREACH = 33;
  public static final int RBRACKET = 78;
  public static final int BEGIN = 26;
  public static final int STRING = 20;
  public static final int AND = 36;
  public static final int PRIVATE = 7;
  public static final int DIFFERS = 41;
  public static final int STATIC = 13;
  public static final int LBRACKET = 77;
  public static final int NAND = 38;
  public static final int EQUALS = 40;
}

