
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 16 12:49:54 EST 2018
//----------------------------------------------------

package lexer_parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 57;
  public static final int IDENTIFIER = 84;
  public static final int POINTER = 59;
  public static final int TYPEOF = 52;
  public static final int CONST = 20;
  public static final int UNTIL = 30;
  public static final int GTHANE = 68;
  public static final int DELEGATE = 21;
  public static final int CONSTRUCTOR = 11;
  public static final int CATCH = 54;
  public static final int COMMA = 58;
  public static final int RBRACE = 77;
  public static final int THROW = 56;
  public static final int RPAREN = 79;
  public static final int INCREMENT = 66;
  public static final int SAGE = 4;
  public static final int LBRACE = 76;
  public static final int LPAREN = 78;
  public static final int PROTECTED = 8;
  public static final int FALSE = 41;
  public static final int NOR = 37;
  public static final int NIL = 43;
  public static final int VAR = 19;
  public static final int FLOAT = 16;
  public static final int MOD = 65;
  public static final int CLASS = 9;
  public static final int STRINGLITERAL = 83;
  public static final int SUPER = 12;
  public static final int UNLESS = 26;
  public static final int FLOATLITERAL = 86;
  public static final int TRUE = 40;
  public static final int PLUS = 60;
  public static final int EXEC = 51;
  public static final int EQUAL = 72;
  public static final int WHILE = 27;
  public static final int EXTENDS = 10;
  public static final int BOOLEAN = 17;
  public static final int DO = 29;
  public static final int FOR = 28;
  public static final int VOID = 14;
  public static final int DIV = 63;
  public static final int PUBLIC = 6;
  public static final int RETURN = 33;
  public static final int MULT = 62;
  public static final int ELSE = 23;
  public static final int TRY = 53;
  public static final int GTHAN = 71;
  public static final int BREAK = 49;
  public static final int DOT = 80;
  public static final int INT = 15;
  public static final int POWER = 64;
  public static final int INTLITERAL = 85;
  public static final int SEMICOLON = 81;
  public static final int EOF = 0;
  public static final int BANG = 73;
  public static final int THIS = 42;
  public static final int LTHAN = 70;
  public static final int PRINT = 47;
  public static final int DECREMENT = 67;
  public static final int MINUS = 61;
  public static final int IN = 32;
  public static final int DEBUG = 48;
  public static final int OR = 35;
  public static final int error = 1;
  public static final int EXIT = 46;
  public static final int START = 2;
  public static final int FINALLY = 55;
  public static final int CONTINUE = 50;
  public static final int IF = 22;
  public static final int LTHANE = 69;
  public static final int END = 3;
  public static final int COLON = 82;
  public static final int RATHER = 25;
  public static final int ASSERT = 44;
  public static final int USING = 5;
  public static final int FOREACH = 31;
  public static final int RBRACKET = 75;
  public static final int BEGIN = 24;
  public static final int NEW = 45;
  public static final int STRING = 18;
  public static final int AND = 34;
  public static final int PRIVATE = 7;
  public static final int DIFFERS = 39;
  public static final int STATIC = 13;
  public static final int LBRACKET = 74;
  public static final int NAND = 36;
  public static final int EQUALS = 38;
}

